--- #YAML:1.0
name:               MCDB_File
version:            0.0102
abstract:           Perl extension for access to mcdb constant databases 
author:
    - gstrauss  <code () gluelogic.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Test::More:  0
resources:
    homepage:    https://github.com/gstrauss/mcdb
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/gstrauss/mcdb
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:  {}
